---
title: "4009week4lecture"
output:html_notebook
---
Ame Liu 22910358
```{r}
library(ggplot2)
library(ggsci)
library(dplyr)
library(gridExtra)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(ggthemes)
library(numform)
library(treemapify)
library(timeDate)
library(lubridate)
library(dplyr)
library(reshape2)
library(ca)
```


1.pairs
矩阵散点图
探索两两变量之间的相关性


```{r}
rw <-read.table('/Users/liuyu/Downloads/winequality-red.csv', head=T,sep=',',fileEncoding = 'UTF-8')
rw
pairs(rw)

```

```{r}
pairs(~pH+alcohol+quality+density, data=rw)
```
只显示下半边数据

```{r}
pairs(~pH+alcohol+quality+density, data=rw,upper.panel = NULL)
```
    
  绘制mpg图像
```{r}
a <- data.frame(mpg)
pairs(~displ+cty+hwy, data=mpg)# mpg是ggplot2的内置数据集

```
  
```{r}
library(ggplot2)
summary(mpg$displ)#mpg的displ数据
ggplot(iris,aes(Sepal.Length,Sepal.Width))+geom_point()+facet_wrap(~Species)#作iris数据集的图
#针对iris数据库进行关于Species的分面处理
ggplot(mpg,aes(displ,hwy))+geom_point(colour='blue')+facet_wrap(~class,ncol = 2)+labs(title = "point geom")#aes是设置横纵坐标,facet_wrap此处为封装型，geom_point()是绘制散点图,tile是设置标题.
ggplot(mpg,aes(displ,hwy))+geom_point(colour='blue')+labs(title = "point geom")#点状图
ggplot(mpg,aes(displ,hwy))+geom_smooth(colour='yellow')+labs(title = "geom_smooth")#平滑图


#通过gridExtra做对比图
p1 <- ggplot(mpg,aes(displ,hwy))+geom_point(colour='blue')+facet_wrap(~class)+labs(title = "point geom")

p2 <- ggplot(mpg,aes(displ,hwy))+geom_smooth(colour='yellow')+labs(title = "geom_smooth")

library(gridExtra)
grid.arrange(p1, p2, ncol=2)

```
展示一下mpg和iris内置数据集，是流行的车的数据
```{r}
rrr <- data.frame(mpg)
rrr
mm <- data.frame(iris)
mm
```


Aesthetic levels
```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, size = class), show.legend = TRUE)

d<- ggplot(mpg,aes(x=displ,y=hwy,size = class))+geom_point(fill = "red",show.legend = TRUE)+labs(title = "point geom") #geom_point1
c <- ggplot(mpg,aes(x=displ,y=hwy,shape = drv,alpha = class))+geom_point(colour='black',fill = "red")+labs(title = "point geom")   #geom_point2

a <- ggplot(mpg,aes(x=displ,y=hwy,group = drv))+geom_smooth(colour='yellow')+labs(title = "geom_smooth")
#geom_smooth1
b <- ggplot(mpg,aes(x=displ,y=hwy,color = drv,linetype = drv))+geom_smooth(colour='yellow')+labs(title = "geom_smooth") #geom_smooth2
grid.arrange(a, b,c, d, ncol=2)
```


```{r}
library(gridExtra)
p1 <- ggplot(data = mpg) +
geom_smooth(mapping = aes(x = displ, y = hwy, group = drv)) #mapping意为映射
p2 <- ggplot(data = mpg) +
geom_smooth(mapping = aes(x = displ, y = hwy, color = drv,
linetype = drv))
p3 <- ggplot(data = mpg) +
geom_point(mapping = aes(x = displ, y = hwy, size = class),
show.legend = TRUE) #显示图例标注
p4 <- ggplot(data = mpg) +
geom_point(mapping = aes(x = displ, y = hwy, alpha = class,
shape = drv))
grid.arrange(p1, p2, p3, p4, ncol=2)
```
```{r}
ggplot(mpg,aes(x = displ, y = hwy))+geom_point()+geom_smooth()
#作图（数据，坐标）+ 选择图形种类
ggplot(mpg,aes(x=displ,y=hwy,color=class))+geom_point()+geom_smooth()
#颜色作为种类的依据

```


Hexbin - 2D histogram geom_hex()为六边形散点图
```{r}


library(hexbin)
a1 <- with(rw,{bin<-hexbin(x=pH,y=density,xbins=10) #xbins的意思为x即是个数，以10个位一组计数
             plot(bin)})

ggplot(rw,aes(pH,density))+geom_smooth(colour='yellow')+labs(title = "geom_smooth")+geom_hex()
#geom_hax()做六边形散点图








```


ggplot2之常见观察变量绘图geom
https://www.jianshu.com/p/4e4f6168fa37

反映频率的图(适合整数)：

```{r}
ggplot(data = rw) +
geom_count(mapping = aes(x=pH, y=density))

```
近似热图

```{r}
library(dplyr)
counting <- count(mpg, displ, hwy)
ggplot(data = counting, mapping = aes(x = displ,y = hwy)) +
geom_tile(mapping = aes(fill = n))#设n为数量
```

适用于这种带类型的变量
```{r}
b <- data.frame(diamonds)
b
library(ggplot2)
ggplot(data = diamonds) +
stat_summary(
mapping = aes(x = cut, y = depth),
fun.ymin = min,
fun.ymax = max,
fun.y = median
)

```

箱型图的使用
```{r}

p1 <- ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
geom_boxplot()
p2 <- ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
geom_boxplot() +
coord_flip()
grid.arrange(p1, p2, ncol=2)
```

Polar coordinate 极坐标的使用
```{r}
bar <- ggplot(data = diamonds) +
geom_bar(
mapping = aes(x = cut, fill = cut),
show.legend = FALSE,
width = 1
) +
theme(aspect.ratio = 1) +
labs(x = NULL, y = NULL)
p1 <- bar + coord_flip()
p2 <- bar + coord_polar()
grid.arrange(p1, p2, ncol=2)
```
地图坐标的使用Map Coordinates coord_quickmap()
```{r}
a <- data.frame(map_data("world"))
a
library(maps)
w <- map_data("world")
p1 <- ggplot(w, aes(long, lat, group = group)) +
geom_polygon(fill = "white", colour = "black")
p2 <- ggplot(w, aes(long, lat, group = group)) +
geom_polygon(fill = "white", colour = "black") +
coord_quickmap()
grid.arrange(p1, p2, ncol=2)
```





