---
title: "week5 pactice"
output: html_notebook
---
数据清洗mutate函数
添加数据列
 

```{r}
library(dplyr)
library(ggplot2)
mpg
mutate(mpg,new_displ=(displ==2.0)
       ) #创建一个新列使得所有displ为2.0的数据变为了NA

count.zero <- sum(mpg$displ == 2.0)
cat("Number of displ having 2.0 : ", count.zero)
## Number
#summary(mpg)
```

使用boxplot观察它认为的异常值
```{r}
stat <- boxplot.stats(mpg$displ)

stat$n      #非NA的数据个数
stat$stat   #数据列中的不同数据的种类
length(stat$out)     #boxplot中认为是异常值的个数
```

讨论NA时所有的数据都会被NA传染
```{r}
NA > 5
10 == NA
NA == NA
#Use is.na() to check if a value is NA or not.
#Use na.omit() to remove incomplete observations
nacounts <- count_missing(mpg)
hasNA = which(nacounts > 0)
nacounts[hasNA]
#vtreat 特征处理
#https://zhuanlan.zhihu.com/p/258396693

```
```{r}
mpg
brks <- c(0,1.5, 3.0, Inf)
mpg$displ.range <- cut(mpg$displ,
breaks=brks, include.lowest=T)
mpg
summary(mpg$displ.range)  #范围数据
mpg$cartype[mpg$displ > 3.0] <- "大排量"
mpg$cartype[mpg$displ > 2.0
& mpg$displ <= 3.0] <- "中排量"
mpg$cartype[mpg$displ <= 2.0] <- "低排量"


```

```{r}
#fix(mpg)


```

Parsing Dates
```{r}
library(Hmisc)
monthDays(as.Date('2020-02-01'))
monthDays(as.Date('2021-02-01'))
monthDays(as.Date('2000-02-01'))
monthDays(as.Date('1900-02-01'))
yearDays(as.Date('1900-02-01'))
mydates <- as.Date(c("2007-06-22", "2004-02-13"))
mydates
class(mydates)
Sys.Date()   #返回今天的日期
date()    #返回现在的时间日期
Sys.time()    #时区
today <- Sys.Date()
format(today, format="%B %d %Y")
format(today, format="%A")
weekdays(Sys.time())
quarters(Sys.time())
julian(Sys.time())#since the originday (1970 Jan 1st)
julian(Sys.time(), origin = as.Date("2021-08-01"))


```
Using dates in calculation
```{r}
#since the originday (1970 Jan 1st)
#早于这个时间的会被列为负值
dob <- as.Date("1956-10-12")
qqq <- as.Date(Sys.time())   #当前日期
as.double(qqq) #距离qqq过去了多少天

dob_num_days <- as.double(dob)
dob_num_days
as.Date(dob_num_days, origin=as.Date("1970-01-01"))   #再转换回去
d <- difftime(today, dob, units="days")     
class(d)      #today和dob差了多少周
d
age <- as.double(d)/365
age
dob <- as.Date("1956-10-12")
as.double((Sys.Date()-dob))/365
as.double(difftime(Sys.Date(), dob, units="days"))/365
```



